### PR TITLE
Suggested: code formatting and refactoring

### PR DESCRIPTION
**Pull request by robbieaverill**
Implemented the Zend style guidelines as per Magento 1.x specifications, refactored some re-used logic, added some documentation.

### CODE REVIEW

**Comment by robbieaverill** [comment]
Hi guys - just a suggested update here to follow Zend standards and removed a little duplicated logic - cheers

**Comment by aligentjim** [comment]
Hi @robbieaverill Thanks for your contribution.  That method has grown organically over time and has been on our radar for re-factoring for quite a while now.  Thanks for taking a swing at it!  We'll do a detailed code review (we run this in production on the vast majority of our sites so we're fairly cautious with changes) and see if we can get that merged in.

Just out of interest, did you happen to take a look at our `v2.0` branch?  It's not ready for production yet, but it shows where we're heading with this extension.  Interested to hear your thoughts if you have a chance to check it out.

cc: @jonpday

**Comment by robbieaverill** [comment]
Hey @aligentjim - thanks for the message. I haven't looked at the 2.0 branch yet, but am happy to take a look at that in the near future.

Cheers,
Robbie

**Comment by robbieaverill** [comment]
Hi @aligentjim - I've pushed another pull request for something similar to the v2.0 branch. I haven't got enough time to port all of these changes over, but have done half of them or so.

**Comment by zainengineer** [comment]
@robbieaverill  can you resolve the conflicts ?

**Comment by robbieaverill** [comment]
Hey @zainengineer - yes, sure I can. I'll take a look in the morning. Cheers

**Comment by robbieaverill** [comment]
All yours @zainengineer

**Comment by zainengineer** [comment]
thanks @robbieaverill  LGTM

**Pull request merged**
